name: RPGTools
main: net.Vala.general.RPGTools
version: 1.0
commands:
  pickaxe:
    description: Spawns your personal pickaxe.
  pick:
    description: Short alternative to /pickaxe.
  rpgtools:
    description: Base command for rpgtools.
  rt:
    description: Short alternative to /rpgtools.